name: nix-flake-check-build
on:
  pull_request:
  push:
  workflow_call:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix flake check -L
  build:
    name: Build - ${{ matrix.attribute }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        attribute:
          - .#devShells.x86_64-linux.default
          - .#nvim
          - .#nvim-dev
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix build "${{ matrix.attribute }}" -L
